### ISSUE TITLE
Hard "No module named 'decorators'" Problem..

### ISSUE THREAD

**Issue by Physalis87** [pgmpy/pgmpy_viz#44]
Dear Ankur Ankan,

could you be so kind and have a look at the error thrown by running _python manage.py runserver_  ?
It is hard for me to trace back to any source, already spent many hours adopting files and versions of packages back and fourth.

Thank you and best
Daniel

```
Exception ignored in thread started by: <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x102d9b040>>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 93, in inner_run
    self.validate(display_num_errors=True)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.9/site-packages/django/core/management/base.py", line 280, in validate
    num_errors = get_validation_errors(s, app)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.9/site-packages/django/core/management/validation.py", line 28, in get_validation_errors
    from django.db import models, connection
  File "/opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.9/site-packages/django/db/__init__.py", line 16, in <module>
    router = ConnectionRouter(settings.DATABASE_ROUTERS)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.9/site-packages/django/db/utils.py", line 117, in __init__
    raise ImproperlyConfigured('Error importing database router %s: "%s"' % (klass_name, e))
django.core.exceptions.ImproperlyConfigured: Error importing database router Neo4djangoIntegrationRouter: "No module named 'decorators'"
```

**My Setting**
ca-certificates           2020.12.5            h4653dfc_0    conda-forge
certifi                   2020.12.5        py39h2804cbe_1    conda-forge
chardet                   4.0.0                    pypi_0    pypi
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
django                    1.5.5                    pypi_0    pypi
freetype                  2.10.4               h17b34a0_1    conda-forge
idna                      2.10                     pypi_0    pypi
jexp                      0.1.2                    pypi_0    pypi
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
kiwisolver                1.3.1            py39h5a63225_1    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcxx                    11.1.0               h168391b_0    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_20    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_20    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libopenblas               0.3.12          openmp_h2ecc587_1    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
libtiff                   4.2.0                h70663a0_0    conda-forge
libwebp-base              1.2.0                h27ca646_2    conda-forge
llvm-openmp               11.1.0               hb3022d6_0    conda-forge
lucene-querybuilder       0.2                      pypi_0    pypi
lz4-c                     1.9.3                h9f76cd9_0    conda-forge
matplotlib                3.3.4            py39hdf13c20_0    conda-forge
matplotlib-base           3.3.4            py39h3e8bbd8_0    conda-forge
mysqlclient               2.0.3                    pypi_0    pypi
ncurses                   6.2                  h9aa5885_4    conda-forge
neo4django                0.1.8                    pypi_0    pypi
neo4jrestclient           2.1.1                    pypi_0    pypi
networkx                  2.5                        py_0    conda-forge
numpy                     1.20.1           py39h69a04d8_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1j               h27ca646_0    conda-forge
pandas                    1.2.3            py39ha4bedbf_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pillow                    8.1.2            py39hf007017_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.9.2           hcbd9b3a_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
readline                  8.1                  hfbdcbf2_0    conda-forge
requests                  2.25.1                   pypi_0    pypi
scikit-learn              0.23.2           py39hb966dd2_3    conda-forge
scipy                     1.6.1            py39h73ea49b_0    conda-forge
setuptools                49.6.0           py39h2804cbe_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.35.2               h6d56c25_0    conda-forge
statsmodels               0.12.2           py39h038c1d3_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
tornado                   6.1              py39h46acfd9_1    conda-forge
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.4                   pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
zstd                      1.4.9                h5b28eab_0    conda-forge

**Comment by ankurankan** [comment]
Hi @Physalis87 , this project hasn't been maintained (and doesn't have many useful features) in a while so I am not sure if there is an easy way to get it back working easily. I am not sure what your usecase is ?, but if you are looking for a graphical way to work with DAGs/bayesian networks, you can also look into http://dagitty.net/

**Comment by Physalis87** [comment]
Hi @ankurankan, thanks a lot for your quick reply and your suggestion. I checked dagitty.net, but as far as I see now it may not meet my requirements. I would like to
- Export the visual graph from graphical editor as a pgmpy (networkx!?) compatible format to use in my code
- Even more so run the pgmpy-Code (and my own implemented Algorithms) interactively with the graphical user interface (I think dagitty does this for d-seperation and other, but I am not sure if I can integrate my stuff there?)

Best, Daniel

**Comment by ankurankan** [comment]
@Physalis87 Yes, you are right. dagitty mainly focuses on the causal interpretation of Bayesian networks. I don't think there is any simple way for your use case right now. This current repo is quite outdated, and you will need to add quite a few features yourself to have everything that you need. If you don't care much about the graphical interface, then you can use the pgmpy package directly.
